db.driver=org.postgresql.Driver
db.dburl=jdbc:postgresql://127.0.0.1:5434/coffeeshop_db
db.user=sa
db.password=admin

db.tablesNames = shifts, staff, coffeeshops
db.sqlScriptCreateTables = src/main/resources/createTables.sql
data.coffeeshops = src/main/resources/coffeeshops.txt
data.names = src/main/resources/names.txt
data.lastnames = src/main/resources/lastname.txt
data.deserts = src/main/resources/deserts.txt
data.drinksAndBeverages = src/main/resources/drinksAndBeverages.txt